app/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

# Define the app name to differentiate between different apps
app_name = 'app'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),

    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),

    path('post/', AddPostView.as_view(), name='post'),


]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(app_urls,namespace='app')),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.
class Post(models.Model):
    text=models.CharField(max_length=140,blank=False,null=False)
    image = ImageField(upload_to='whatever')
    def __str__(self):
        return self.text

app/forms.py
from django import forms

class PostForm(forms.Form):
    image=forms.FileField()
    text=forms.CharField(label="Description")

app/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import TemplateView, DetailView, FormView
from .forms import PostForm
from django.contrib import messages

# Create your views here.

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        # ? Method to fetch context data for the template
        context = super().get_context_data(**kwargs)

        #? Fetch all Post objects from the database
        context['posts'] = Post.objects.all().order_by('-id')
        return context

class PostDetailView(DetailView):
    #& View for rendering individual post detail pages
    template_name = 'detail.html'
    model = Post

class AddPostView(FormView):
    template_name='new_post.html'
    form_class=PostForm
    success_url='/'

    def dispatch(self,request,*args,**kwargs):
        self.request=request
        return super().dispatch(request,*args,**kwargs)

    def form_valid(self, form):

        new_object=Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request,messages.SUCCESS,'Your post was successfull')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Document{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
</head>

<body>
    {% include 'includes/navbar.html' %}

    {% if messages %}
        {% for message in messages %}
        <div
            class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %} bg-gradient text-center text-white py-4">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %} 

    <div class="container">
        {% block body %}{% endblock body %}
    </div>
</body>

</html>

templates/detail.html
{% extends 'base.html' %}
{% block title %}
    Detail View
{% endblock title %}

{% block body %}
<!-- Starting the body block -->
    <div class="row">
        <div class="col-sm-10 offset-sm-1 py-5">
            {{ object.text }}
            <img src="{{ object.image.url }}" class="img-fluid rounded">
            <!-- Displaying the image associated with the post -->

        </div>
    </div>

{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block body %}

    <div class="row">

        {% for post in posts %}
            <div class="col-sm-6 col-md-3">

                <div class="card mb-4 mt-4">
                    {% thumbnail post.image "500x300" crop="center" as im %}
                    <!-- Generating a thumbnail of the post's image -->
                        <img src="{{ im.url }}" class="card-img-top" alt="...">
                    {% endthumbnail %}
                    <div class="card-body">
                    <p class="card-text"> {{ post.text }}</p>
                    <a href="{% url 'app:detail' post.id %}" class="btn btn-primary">View Full Image</a>
                    </div>
                 </div>
            </div>
        
        {% empty %}
            <div class="col-sm-6 offset-3 text-center py-5 my-5">
                <h3>Welcome</h3>
                <p>Add your first image</p>
                <a href="{% url 'app:post' %}" class="btn btn-lg btn-success">Upload Image</a>
            </div>
            
        {% endfor %}

    </div>

{% endblock body %}

{% block title %} HomePage {% endblock title %}

templates/includes/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Share</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Image Share</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'app:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app:post' %}">Add New Image</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    </body>

</html>

templates/new_post.html
{% extends 'base.html' %}
{% block title %}
    Image Upload
{% endblock title %}

{% block body %}
<!-- Starting the body block -->

    <form action="" method="post" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
        <h2>Upload an Image</h2>
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <button type="submit" class="btn btn-lg btn-success">Submit Form</button>
        </div>
    </form>

{% endblock body %}